//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracBilgileri
    {
        public int Id { get; set; }
        public string AracAdi { get; set; }
        public string AracBilgisi { get; set; }
        public int Fiyati { get; set; }
        public string AracResmi { get; set; }
    }
}
