//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiralayan
    {
        public int Id { get; set; }
        public string IsimSoyisim { get; set; }
        public string Adres { get; set; }
        public Nullable<double> TCKN { get; set; }
        public Nullable<double> Tel1 { get; set; }
        public Nullable<double> Tel2 { get; set; }
        public string EMail { get; set; }
        public string KiralayacagiArac { get; set; }
    }
}
