//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AracKiralamaDBEntities : DbContext
    {
        public AracKiralamaDBEntities()
            : base("name=AracKiralamaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AracBilgileri> AracBilgileris { get; set; }
        public virtual DbSet<Kiralayan> Kiralayans { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
    }
}
